services:
  web:
    image: global-digital:1.0.0
    build: 
      context: .
      target: dev
    ports:
      - ${WEB_PORT:-3000}:3000

  postgres:
    image: postgres:alpine
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_DB=${DB_NAME:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
