services:
  s3:
    command: minio server /data --console-address ":9001"
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
  postgres:
    image: postgres:alpine
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_DB=${DB_NAME:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
