apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: global-digital
  name: global-digital
  namespace: app-ns
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: global-digital
  type: LoadBalancer
status:
  loadBalancer: {}
